# Generated by Django 4.1.7 on 2023-03-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=100)),
                ('menorNombre', models.CharField(max_length=100)),
                ('menorApellido', models.CharField(max_length=100)),
                ('fecha_nacimientoMenor', models.CharField(max_length=100)),
            ],
        ),
    ]
